title: Robert's strong momentum
description: A powerful moment in my life. These moment make strong momentum.
author: Robert Koh
avatar: /logo.jpeg
email: rhdudwns0@naver.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
#
# google_analytics:

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
#
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: logo.jpeg
social:
  name: Robert Koh
  links:
    - https://www.instagram.com/_june_journey__/
    - https://github.com/yeongjunekoh
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: ko
